### ISSUE TITLE
Change packagename

### ISSUE THREAD

**Issue by BaseMax** [Asrez/WhereMoneyAPI#2]
New name: `com.asrez.wheremoney.api`

**Comment by RishiKumarRay** [comment]
Which package name do we have to change

**Comment by BaseMax** [comment]
Hi there, welcome.
Changing `com.wheremoney.demo` to `com.asrez.wheremoney.api`.

**Comment by amir-shiati** [comment]
Done. 12cc4ac250fa2c2290aa9c60e085aea68c6699af
