### ISSUE TITLE
Connecting with the database

### ISSUE THREAD

**Issue by mohabsherif** [Asrez/WhereMoneyAPI#3]
![Screenshot_2](https://user-images.githubusercontent.com/74313923/156353471-969693c5-0e90-48ca-926f-a580c754db51.png)

I have changed the port number as shown in the ss because my default Postgres port is that also changed the username and password.

The problem here is that when I run
 java -jar jars/where-money-api.jar --spring.config.location=./src/main/resources/application.yml
 it gives me error
![Screenshot_3](https://user-images.githubusercontent.com/74313923/156353840-cf35984f-ca2b-40cb-b066-bedae61f222d.png)
When I then try to change the port number it gives me another error (idk if it's ok to change to another port that Postgres is not running on it)
![image](https://user-images.githubusercontent.com/74313923/156355084-e0616387-fc5e-4c06-92a4-88df4de57477.png)

**Comment by BaseMax** [comment]
Application.yml file:

```
server:
     port: 8090
```
