### ISSUE TITLE
Running into CORS problems

### ISSUE THREAD

**Issue by mohabsherif** [Asrez/WhereMoneyAPI#4]
![image](https://user-images.githubusercontent.com/74313923/156412404-e5158a12-985b-4df4-b633-1d0b49323fb5.png)
After installing unblock CORS plugin for my browser i get this

**Comment by BaseMax** [comment]
https://spring.io/guides/gs/rest-service-cors/

https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by BaseMax** [comment]
maybe:
```
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.web.cors.CorsConfiguration;

import java.util.List;

@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter
{


    @Override
    protected void configure(HttpSecurity http) throws Exception {
        CorsConfiguration corsConfiguration = new CorsConfiguration();
        corsConfiguration.setAllowedHeaders(List.of("Authorization", "Cache-Control", "Content-Type"));
        corsConfiguration.setAllowedOrigins(List.of("*"));
        corsConfiguration.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "PUT","OPTIONS","PATCH", "DELETE"));
        corsConfiguration.setAllowCredentials(true);
        corsConfiguration.setExposedHeaders(List.of("Authorization"));
        
        // You can customize the following part based on your project, it's only a sample
        http.authorizeRequests().antMatchers("/**").permitAll().anyRequest()
                .authenticated().and().csrf().disable().cors().configurationSource(request -> corsConfiguration);

    }
}```

**Comment by BaseMax** [comment]
Hey Amir, please check the issue. @amir-shiati

**Comment by amir-shiati** [comment]
Hey. @muuhab 
I've fixed the issue.
Can you please do a git pull and inform me whether the problem has been solved for you or not?
Thank you.

**Comment by mohabsherif** [comment]
Hey @amir-shiati,

I've tried it again but it gives me the same error

> ![image](https://user-images.githubusercontent.com/74313923/156412404-e5158a12-985b-4df4-b633-1d0b49323fb5.png) After installing unblock CORS plugin for my browser i get this

**Comment by amir-shiati** [comment]
Hey, @muuhab 
Please retry and let me know if your still facing the same problem.
Thanks.

**Comment by mohabsherif** [comment]
> Hey, @muuhab Please retry and let me know if your still facing the same problem. Thanks.

I'm still having this problem

**Comment by mohabsherif** [comment]
Also,  "/auth/login" was working well but now it gives the same error like the above.

**Comment by amir-shiati** [comment]
@muuhab 
Hey man, Sorry for the inconvenience. everything should be fine now.
Please let me know the results.
Thanks again.

**Comment by mohabsherif** [comment]
@amir-shiati 
Hey, I'm very sorry to say that it still exists but the good thing is that the "auth/login" is back to working well. 
And no problem man, it's okay.
Thank you.

**Comment by amir-shiati** [comment]
@muuhab 
I've added a CorsConfig class now. Please retry.
Are you working on [WhereMoney](https://github.com/Asrez/WhereMoney) right now?
I would like to be able to run the source code myself so i can debug this problem better.
Thank you.

**Comment by mohabsherif** [comment]
@amir-shiati 
Unfortunately still the same.
I'm working on it. but you can run the source so it's better to debug.

**Comment by amir-shiati** [comment]
@muuhab 
I was able to run the WhereMoney react application on my machine, I've added a  filter to request to allow for CORS, can you please retry one more time?
If you're still facing the same problem, can you please let me know how can i do a test inside your application for debug purposes?
Thanks.

**Comment by mohabsherif** [comment]
@amir-shiati  
It's working now.
Thank you.

**Comment by amir-shiati** [comment]
@muuhab 
FINALLY!
It took me way too long man :))), Thanks for you patience.
