### ISSUE TITLE
Getting more info

### ISSUE THREAD

**Issue by mohabsherif** [Asrez/WhereMoneyAPI#5]
![unknown](https://user-images.githubusercontent.com/74313923/156924198-9cd7249b-9802-4e11-aeef-35a382619c98.png)
![unknown2](https://user-images.githubusercontent.com/74313923/156924201-fe61c83e-33da-4c43-bc2c-e59aeaa305c3.png)

These are the parameters of a single transaction, there is a difference between what we implemented and the backend database. so, what should I do?
These icons what do they refer to(Which database column?, What types they should take?). 
Also, Sign up requires to be authenticated. How would I make it if there is no token for the guest users?

**Comment by amir-shiati** [comment]
Hey @muuhab,
I'm gonna add a new table for handling types as soon as i can. I'll let you know when the changes have been made.
Also signing up is mandatory in order to use the application, so there is no need for guest tokens.

**Comment by mohabsherif** [comment]
Hey @amir-shiati,

I mean when signing up it needs to be authenticated (normal sign up gives me 401 unauth), though I need to provide a token to be able to sign up. What is the solution?

**Comment by amir-shiati** [comment]
@muuhab 
As of right now only users with admin role can add other users, you can use the auth token of the default admin user that was automatically created the first time you executed the web service.
Or we can simply allow anyone to sign up without requiring auth token.
what do you guys think @BaseMax @muuhab ?

**Comment by mohabsherif** [comment]
> ![unknown](https://user-images.githubusercontent.com/74313923/156924198-9cd7249b-9802-4e11-aeef-35a382619c98.png) ![unknown2](https://user-images.githubusercontent.com/74313923/156924201-fe61c83e-33da-4c43-bc2c-e59aeaa305c3.png)
> 
> These are the parameters of a single transaction, there is a difference between what we implemented and the backend database. so, what should I do? These icons what do they refer to(Which database column?, What types they should take?). Also, Sign up requires to be authenticated. How would I make it if there is no token for the guest users?

- account number doesn't exist on the user table, for that, I need to make the user enter it. Is it okay like this?
- destination and source, what should I provide in the form for them?

**Comment by mohabsherif** [comment]
> @muuhab As of right now only users with admin role can add other users, you can use the auth token of the default admin user that was automatically created the first time you executed the web service. Or we can simply allow anyone to sign up without requiring auth token. what do you guys think @BaseMax @muuhab ?

Using the admin token would give the user all access. I believe we can make users sign up without token and give them a lower role.

**Comment by amir-shiati** [comment]
> > ![unknown](https://user-images.githubusercontent.com/74313923/156924198-9cd7249b-9802-4e11-aeef-35a382619c98.png) ![unknown2](https://user-images.githubusercontent.com/74313923/156924201-fe61c83e-33da-4c43-bc2c-e59aeaa305c3.png)
> > These are the parameters of a single transaction, there is a difference between what we implemented and the backend database. so, what should I do? These icons what do they refer to(Which database column?, What types they should take?). Also, Sign up requires to be authenticated. How would I make it if there is no token for the guest users?
> 
> * account number doesn't exist on the user table, for that, I need to make the user enter it. Is it okay like this?
> * destination and source, what should I provide in the form for them?

@muuhab 
While setting up the database me and @BaseMax decided to add those filed as well. However the only required fields for transaction are "price", "is_income" & "calculate_in_monthly" you can leave all the other ones empty.

**Comment by amir-shiati** [comment]
> > @muuhab As of right now only users with admin role can add other users, you can use the auth token of the default admin user that was automatically created the first time you executed the web service. Or we can simply allow anyone to sign up without requiring auth token. what do you guys think @BaseMax @muuhab ?
> 
> Using the admin token would give the user all access. I believe we can make users sign up without token and give them a lower role.

Yeah, agreed. I'll make the changes and let you know.

**Comment by mohabsherif** [comment]
Ok, Thank you @amir-shiati

**Comment by amir-shiati** [comment]
@muuhab 
Now you can add users without having auth token.

**Comment by mohabsherif** [comment]
I have added pagination but I don't know the number of pages as fetching transactions only fetch 10 per request. so, how do I get the total number of transactions? any ideas? @amir-shiati, @BaseMax

**Comment by mohabsherif** [comment]
![image](https://user-images.githubusercontent.com/74313923/156952424-adeb77f9-2624-4ab5-8d34-e00fc13f7858.png)
Filtering transactions by date will be applied on 10 transactions only as I'm not fetching all transactions.
What do you think I can do in this situation?

**Comment by BaseMax** [comment]
I think we can increase the page number until we get empty results? so we
stopped and infinity scrolling stopped. yeah?

**Comment by amir-shiati** [comment]
Hey @muuhab 
If the response array list is empty, that indicates there are no more transactions.
Also you can use "page_size" parameter to set the number of transactions you would like to fetch per request (the default is 10).

**Comment by amir-shiati** [comment]
Hey @muuhab 
Type table and its controller have been added to the project.
Now you can get a list of types, show them to the user and set a "type_id" for each transaction.
Also there is an "icon_name" field so you can map each type to its icon.
Users with admin role can add or delete a new type while users with user role can only get a list of types.
I'll advise you to delete all transaction in your transaction table before running the web service because of the not null constraint  of the "type_id" column.
