### ISSUE TITLE
Transactions fetching error

### ISSUE THREAD

**Issue by mohabsherif** [Asrez/WhereMoneyAPI#8]
Hey @amir-shiati,
After the last update, I have fetched types but when I checked for fetching or adding transactions I get a 500 Internal Server Error.

![image](https://user-images.githubusercontent.com/74313923/157279452-e2737a9e-79fa-4fc8-ae4d-bbfbcee924e6.png)
![image](https://user-images.githubusercontent.com/74313923/157279547-3f6c0a71-b6fb-4213-8b7a-744938fa9259.png)

Also, I can't find type_id on the transactions table.
![image](https://user-images.githubusercontent.com/74313923/157279664-d32dd5a9-6c54-44e9-85df-2b07f7c03625.png)

PS: I have deleted all transactions tho.

**Comment by mohabsherif** [comment]
Hey @amir-shiati,
Could you please add the new endpoints and tables to the documentation?

**Comment by amir-shiati** [comment]
Hey @muuhab 
Documentation has been updated, check it out [here](https://asrez.github.io/SwaggerUI/?url=https://asrez.github.io/WhereMoneyAPI/docs/swagger.yaml).
Also, i suggest dropping the transactions table and re running the web service after doing that.
